Flappy Bird Overhaul
TigardHighGDC/FlappyBird pull request #13
Opened 2022-10-28 01:21 UTC by Galaxy25

Closes #3 
Closes #2 
A general overhaul to flappy bird. Creates movable pipes that repeatably spawn. Movement matches the original flappy bird. The bird dies on collision.

2022-10-28 01:21 UTC, Galaxy25 commented
Approved

2022-10-28 18:45 UTC, BrandonPacewic commented
@Galaxy25 Looks like there are some merge conflicts with `Assets/Scenes/SampleScene.unity`

2022-10-28 19:03 UTC, Galaxy25 commented
@BrandonPacewic Forgot to rename the scene so GitHub wouldn't try to merge them together. It should now work. Also I ran clang.

2022-10-28 20:18 UTC, BrandonPacewic requested changes
General nitpicks. I'll push a fix in a few minutes.

2022-10-28 20:18 UTC, BrandonPacewic commented on Assets/Scripts/Movement.cs
> +using System.Collections;
Need to add our copyright

2022-10-28 20:18 UTC, BrandonPacewic commented on Assets/Scripts/PipeMovement.cs
> +using System.Collections;
Copyright.

2022-10-28 20:18 UTC, BrandonPacewic commented on Assets/Scripts/Spawn.cs
> +using System.Collections;
Copyright

2022-10-28 20:18 UTC, BrandonPacewic commented on Assets/Scripts/PipeMovement.cs
> +    void Update()
```suggestion
    private void Update()
```

2022-10-28 20:18 UTC, BrandonPacewic commented on Assets/Scripts/Spawn.cs
> +    void Start()
```suggestion
    private void Start()
```

2022-10-28 20:18 UTC, BrandonPacewic commented on Assets/Scripts/Spawn.cs
> +    void Update()
```suggestion
    private void Update()
```

2022-10-28 20:18 UTC, BrandonPacewic commented on Assets/Scripts/Movement.cs
> +    void Update()
```suggestion
    private void Update()
```

2022-10-28 20:18 UTC, BrandonPacewic commented on Assets/Scripts/Movement.cs
> +    void OnTriggerEnter2D(Collider2D trigger)
```suggestion
    }
   
    private void OnTriggerEnter2D(Collider2D trigger)
```

2022-10-28 20:27 UTC, BrandonPacewic commented
Also updated to Unity version `2021.3.12f1`.

2022-10-28 20:30 UTC, BrandonPacewic requested changes
If we have a variable public then shouldn't it be set from the object settings rather than a fixed value?

2022-10-28 20:30 UTC, BrandonPacewic commented on Assets/Scripts/Movement.cs
> +    public bool canJump = true;
Do these need to be public?

2022-10-28 20:30 UTC, BrandonPacewic commented on Assets/Scripts/PipeMovement.cs
> +    public float speed = 5f;
Does this need to be public?

2022-10-28 20:30 UTC, BrandonPacewic commented on Assets/Scripts/Spawn.cs
> +    public float endTimer = 5f;
Does this need to be public?

2022-11-01 19:54 UTC, Galaxy25 commented
Having a public variable makes it easier to edit within Unity allowing it to be tweaked faster. Since the game was a test and not a multiple-month project rechanging the variables would cause more problems than preventing future ones.

2022-11-01 19:55 UTC, Galaxy25 commented
Also another use case for public variables would be allowing different types of information upon the game object creation. For example enemies with varying movement speed

2022-11-01 20:19 UTC, BrandonPacewic submitted a review, later dismissed

2022-11-01 20:21 UTC, BrandonPacewic commented
I'm getting ready to merge and updating the change log - please @me if any other changes are pushed.

2022-11-01 20:33 UTC, BrandonPacewic commented
@Galaxy25 Before I merge, is it correct to leave `Flying.cs` in addition to `Movement.cs`?

2022-11-01 21:19 UTC, Galaxy25 commented
Flying.cs needs to be removed.
Then Approved

2022-11-01 21:48 UTC, BrandonPacewic approved these changes
In the future I will want to discuss file naming. For instance:

- `Movement.cs` -> `BirdMovementController.cs`
- `PipeMovement.cs` -> `PipeMovementController.cs`
- `Spawn.cs` -> `PipeSpawner.cs`

But like you said, this is supposed to be janky for now 🙃

2022-11-01 21:49 UTC, merged

2022-11-01 21:50 UTC, BrandonPacewic commented
Thanks for getting this done! Next time we should get @JakeSmig to help with the review process 🖥️