Bird Flying
TigardHighGDC/FlappyBird pull request #6
Opened 2022-10-07 01:25 UTC by Galaxy25

2022-10-07 01:29 UTC, Galaxy25 reviewed
Appears to be working

2022-10-07 01:30 UTC, BrandonPacewic commented
Hey thanks for the changes, give me some time to look at your changes. Super excited! Feel free to ask me any questions! :bird:

2022-10-07 01:31 UTC, BrandonPacewic commented
Auto response test

2022-10-07 01:53 UTC, BrandonPacewic commented on Assets/Scripts/Flying.cs
> +    // Update is called once per frame
This comment is unnecessary and should always be removed.
```suggestion
```

2022-10-07 01:53 UTC, BrandonPacewic commented on Assets/Scripts/Flying.cs
> +    // Start is called before the first frame update
Same as other comment.
```suggestion
```

2022-10-07 01:54 UTC, BrandonPacewic commented on Assets/Scripts/Flying.cs
> +    float force = 10.0f;
Should these variables be private or public?

```suggestion
    private float force = 10.0f;
    private bool hit = true;
```

2022-10-07 01:55 UTC, BrandonPacewic commented on Assets/Scripts/Flying.cs
> +using System.Collections;
Need to add our copyright to the top
```suggestion
// Copyright (c) TigardHighGDC
// SPDX-License SPDX-License-Identifier: Apache-2.0

using System.Collections;
```

2022-10-07 01:56 UTC, BrandonPacewic commented on Assets/Scripts/Flying.cs
> +    void Start()
Do we really need start?

2022-10-07 01:56 UTC, BrandonPacewic commented on Assets/Scripts/Flying.cs
> +    void Update()
Should be private
```suggestion
    private void Update()
```

2022-10-07 01:58 UTC, BrandonPacewic requested changes
Lets look at removing start and the update comment. Seems unnecessary.

2022-10-07 15:44 UTC, BrandonPacewic approved these changes
@Galaxy25 Looks good to me, although in the future I would like to only add code that we know works and can be ran.

Since you can't review your own PR just add a comment like:

**Approve** ✅

So I know that you are ok with the PR

2022-10-08 19:11 UTC, Galaxy25 commented
Aprove

2022-10-09 21:24 UTC, BrandonPacewic commented
I'm getting ready to merge and updating the change log - please @me if any other changes are pushed.

2022-10-09 22:08 UTC, merged

2022-10-09 22:08 UTC, BrandonPacewic commented
Thanks for getting everyone started on this! I can't wait to get everything rolling this year 🚀